### ISSUE TITLE
Not working on Linux Envirotment

### ISSUE THREAD

**Issue by vitorcampea** [pug-pelle-p/pugpdf#10]
It is not working on linux, tried aloot of things, had to import a new version of wkhtmltopdf  that i found on the web and got it working for me.

This repository has "wkhtmltopdf 0.12.4" version and i had to create a docker image with "wkhtmltopdf 0.12.5 (with patched qt)"

Dockerfile
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base

...

// Install wkhtmltopdf dependencies
RUN apt-get update && apt-get install -y \
    xvfb \
    libfontconfig \
    wkhtmltopdf \
    libxrender1 \
    libgdiplus \
    libc6-dev

...

// copy a working linux binary of wkhtmltopdf
// wkhtmltopdf 0.12.5 (with patched qt) - 
// this is where i replace your wkhtmltopdf for a latest version
RUN cp newVersionFileForLinux /app/wkhtmltopdf/linux/x64/wkhtmltopdf`

**Comment by DoganTahir** [comment]
can you work in linux environment with this solution now if you are working I will have to apply the same solution.
@vitorcampea

**Comment by pug-pelle-p** [comment]
For using this in docker (linux) you might need to install some dependencies depending on your linux environment.
We are using asp.net alpine image and for that we need to install the following:
RUN apk add --no-cache \
  libstdc++=10.3.1_git20210424-r2 \
  libx11 \
  libxrender \
  libxext \
  libssl1.1 \
  ca-certificates \
  fontconfig \
  freetype \
  ttf-dejavu \
  ttf-droid \
  ttf-freefont \
  ttf-liberation \
  ttf-ubuntu-font-family \

**Comment by eduhza** [comment]
Could not make it work on docker: System.Exception: /app/bin/Debug/net8.0/wkhtmltopdf/linux/x64/wkhtmltopdf: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory

   at PugPdf.Core.WkHtmlToPdfDriver.ConvertAsync(String html, String switches)
   at PugPdf.Core.HtmlToPdf.RenderHtmlAsPdfAsync(String html)

Here is my dockerfile:

# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["PocUi.csproj", "."]
RUN dotnet restore "./PocUi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./PocUi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./PocUi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app

# Install wkhtmltopdf dependencies for Linux
USER root
RUN apt-get update && apt-get install -y \
    libfontconfig \
    wkhtmltopdf \
    libxrender1 \
    libgdiplus \
    libc6-dev \

RUN apk add --no-cache \
libstdc++=10.3.1_git20210424-r2 \
libx11 \
libxrender \
libxext \
libssl1.1 \
ca-certificates \
fontconfig \
freetype \
ttf-dejavu \
ttf-droid \
ttf-freefont \
ttf-liberation \
ttf-ubuntu-font-family \

# Copy the published application
COPY --from=publish /app/publish .

# Switch back to the non-root user if necessary
USER app

# Set the entrypoint to run the application
ENTRYPOINT ["dotnet", "PocUi.dll"]

**Comment by eduhza** [comment]
I managed to get it working using the provided dockerfile in https://www.nrecosite.com/pdf_generator_net.aspx.

```
RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates fontconfig libc6 libfreetype6 libjpeg62-turbo libpng16-16 libssl3 libstdc++6 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base zlib1g
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb
RUN dpkg -i wkhtmltox_0.12.6.1-3.bookworm_amd64.deb
```

Do NOT install wkhtmltopdf via apt-get install -y wkhtmltopdf because most likely you'll install legacy (old) version and possibly a wrong build (without 'patched' QT).
