### ISSUE TITLE
Executable not found in dotnet core 5

### ISSUE THREAD

**Issue by melbin97** [pug-pelle-p/pugpdf#14]
[16:05:26 INF] Exporting process started....
[16:05:47 ERR] Exception Message = Executable not found.
 StackTrace =   at PugPdf.Core.WkHtmlToPdfDriver.GetPath()
   at PugPdf.Core.WkHtmlToPdfDriver.ConvertAsync(String html, String switches)
   at PugPdf.Core.HtmlToPdf.RenderHtmlAsPdfAsync(String html)

**Comment by pug-pelle-p** [comment]
I'm assuming that the code is copying the file to the incorrect folder. I'm thinking of instead doing this in the nuget project, just include the binary within the application and unpack it on initial run. But I haven't gotten around to it, so if someone wants to help out with this I'm more than happy to approve a PR for that
