### ISSUE TITLE
Executeable not found in dotnet Net6 core

### ISSUE THREAD

**Issue by rhourani-kassavirtanen** [pug-pelle-p/pugpdf#15]
Debugged the code locally and the path of the wkhtmltopdf.exe points to a folder outside the project, "AppData\Local\AzureFunctionsTools\Releases\4.10.1\cli_x64"

It works when you place the executable file there but I could not now where is points when deploying the code to the server

**Comment by rhourani-kassavirtanen** [comment]
After many hours of debugging, it looks in this directory: 

System.IO.FileNotFoundException: Executable not found.
Application:File name: 'D:\Program Files (x86)\SiteExtensions\Functions\4.0.1\64bit\wkhtmltopdf\windows\x64\wkhtmltopdf.exe'
Application:   at PugPdf.Core.WkHtmlToPdfDriver.GetPath()
Application:   at PugPdf.Core.WkHtmlToPdfDriver.ConvertAsync(String html, String switches)
Application:   at PugPdf.Core.HtmlToPdf.RenderHtmlAsPdfAsync(String html)

**Comment by pug-pelle-p** [comment]
I'm assuming that the code is copying the file to the incorrect folder. I'm thinking of instead doing this in the nuget project, just include the binary within the application and unpack it on initial run. But I haven't gotten around to it, so if someone wants to help out with this I'm more than happy to approve a PR for that

**Comment by tnlthanzeel** [comment]
@rhourani-kassavirtanen , were you able to find a solution for this?
